FROM python:3.11-slim

# إنشاء مجلد العمل
WORKDIR /app

# نسخ متطلبات المشروع وتثبيتها
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# نسخ ملفات المشروع
COPY . .

# تشغيل التطبيق باستخدام gunicorn
CMD ["gunicorn", "tourism_project.wsgi:application", "--workers", "4", "--bind", "0.0.0.0:8000"]
