# Generated by Django 5.2 on 2025-04-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_message_nl_contactmessage_message_de_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='contactmessage',
        #     old_name='message_nl',
        #     new_name='message_de',
        # ),
        # migrations.RenameField(
        #     model_name='contactmessage',
        #     old_name='subject_nl',
        #     new_name='subject_de',
        # ),
        # migrations.RenameField(
        #     model_name='currency',
        #     old_name='name_nl',
        #     new_name='name_de',
        # ),
        # migrations.RenameField(
        #     model_name='faq',
        #     old_name='answer_nl',
        #     new_name='answer_de',
        # ),
        # migrations.RenameField(
        #     model_name='faq',
        #     old_name='question_nl',
        #     new_name='question_de',
        # ),
        # migrations.RenameField(
        #     model_name='notification',
        #     old_name='message_nl',
        #     new_name='message_de',
        # ),
        # migrations.RenameField(
        #     model_name='notification',
        #     old_name='title_nl',
        #     new_name='title_de',
        # ),
        # migrations.RenameField(
        #     model_name='sitesetting',
        #     old_name='about_us_nl',
        #     new_name='about_us_de',
        # ),
        # migrations.RenameField(
        #     model_name='sitesetting',
        #     old_name='address_nl',
        #     new_name='address_de',
        # ),
        # migrations.RenameField(
        #     model_name='sitesetting',
        #     old_name='privacy_policy_nl',
        #     new_name='privacy_policy_de',
        # ),
        # migrations.RenameField(
        #     model_name='sitesetting',
        #     old_name='site_name_nl',
        #     new_name='site_name_de',
        # ),
        # migrations.RenameField(
        #     model_name='sitesetting',
        #     old_name='terms_conditions_nl',
        #     new_name='terms_conditions_de',
        # ),
        # Avoid manual RenameField with modeltranslation, especially on SQLite.
        # modeltranslation handles schema changes based on models and settings.
    ]
